In [1]:
import os
import sys
sys.path.append("../")
from concerto_function5_3 import *
from sklearn.metrics import f1_score, accuracy_score
import numpy as np
import scanpy as sc
import matplotlib.pyplot as plt

In [2]:
#Select an available GPU to run on a multi-GPU computer or you can run it directly on the CPU without executing this cell
import tensorflow as tf
os.environ["CUDA_VISIBLE_DEVICES"] = '7' 
gpus = tf.config.experimental.list_physical_devices(device_type='GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True) 

In [3]:
path = './TMS_filtered_100k_noNA.loom'
adata = sc.read(path)

In [4]:
adata = preprocessing_rna(adata, is_hvg=True,batch_key='tissue')
print('finish preprocessing')

... storing 'FACS.selection' as categorical
... storing 'age' as categorical
... storing 'batch' as categorical
... storing 'cell' as categorical
... storing 'cell_ontology_class' as categorical
... storing 'cell_ontology_class_reannotated' as categorical
... storing 'cell_ontology_id' as categorical
... storing 'cellid' as categorical
... storing 'free_annotation' as categorical
... storing 'free_annotation_reannotated' as categorical
... storing 'label' as categorical
... storing 'method' as categorical
... storing 'mouse.id' as categorical
... storing 'plate' as categorical
... storing 'sex' as categorical
... storing 'subtissue' as categorical
... storing 'tissue' as categorical
... storing 'well' as categorical
/home/CXxie/.conda/envs/py36/lib/python3.6/site-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/in

Processed dataset shape: (94793, 2000)
finish preprocessing


In [5]:
# make tfrecord
concerto_make_tfrecord_supervised(adata,tf_path = './tfrecord/tissue_hvg/',batch_col_name='tissue',label_col_name='label')

counter: 100 shape: (2000,), batch: 2
[9.9999997e-06 9.9999997e-06 9.9999997e-06 ... 9.9999997e-06 1.6477810e-02
 5.6498576e-02]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 1.64778102e-02 5.64985760e-02]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 200 shape: (2000,), batch: 2
[9.9999997e-06 9.9999997e-06 9.9999997e-06 ... 9.9999997e-06 9.9999997e-06
 1.6379253e+00]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 1.63792527e+00]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 300 shape: (2000,), bat

counter: 1900 shape: (2000,), batch: 4
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 2000 shape: (2000,), batch: 0
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 2100 shape: (2000,), batch: 6
[9.9999997e-06 9.9999997e-06 9.9999997e-06 ... 2.9808314e+00 9.9999997e-06
 2

counter: 3800 shape: (2000,), batch: 11
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 3900 shape: (2000,), batch: 10
[1.000000e-05 1.000000e-05 1.000000e-05 ... 8.006202e-01 1.000000e-05
 1.000000e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 8.00620198e-01
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 4000 shape: (2000,), batch: 10
[9.9999997e-06 9.9999997e-06 9.999999

counter: 5600 shape: (2000,), batch: 9
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 5700 shape: (2000,), batch: 9
[1.000000e-05 1.000000e-05 8.568595e-03 ... 1.000000e-05 1.000000e-05
 2.840336e-01]
[9.99999975e-06 9.99999975e-06 8.56859516e-03 ... 9.99999975e-06
 9.99999975e-06 2.84033597e-01]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 5800 shape: (2000,), batch: 9
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 

counter: 7400 shape: (2000,), batch: 10
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 7500 shape: (2000,), batch: 9
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 7600 shape: (2000,), batch: 9
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-

counter: 9300 shape: (2000,), batch: 10
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 9400 shape: (2000,), batch: 10
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 9500 shape: (2000,), batch: 9
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e

counter: 11100 shape: (2000,), batch: 10
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 11200 shape: (2000,), batch: 13
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 11300 shape: (2000,), batch: 10
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999

counter: 13000 shape: (2000,), batch: 17
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 13100 shape: (2000,), batch: 17
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 13200 shape: (2000,), batch: 17
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999

counter: 14800 shape: (2000,), batch: 17
[9.9999997e-06 9.9999997e-06 9.9999997e-06 ... 9.9999997e-06 1.0313898e+00
 9.9999997e-06]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 1.03138983e+00 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 14900 shape: (2000,), batch: 17
[9.9999997e-06 9.3208134e-01 9.9999997e-06 ... 9.9999997e-06 9.9999997e-06
 3.6460638e-01]
[9.99999975e-06 9.32081342e-01 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 3.64606380e-01]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 15000 shape: (200

counter: 16600 shape: (2000,), batch: 12
[1.000000e-05 1.000000e-05 7.163766e-01 ... 1.000000e-05 1.000000e-05
 1.000000e-05]
[9.99999975e-06 9.99999975e-06 7.16376603e-01 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 16700 shape: (2000,), batch: 9
[3.6024773e-01 9.9999997e-06 9.9999997e-06 ... 9.9999997e-06 9.9999997e-06
 9.9999997e-06]
[3.60247731e-01 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 16800 shape: (2000,), ba

counter: 18400 shape: (2000,), batch: 3
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 18500 shape: (2000,), batch: 15
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 18600 shape: (2000,), batch: 16
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.999999

counter: 20300 shape: (2000,), batch: 15
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 20400 shape: (2000,), batch: 17
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 20500 shape: (2000,), batch: 16
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999

counter: 22200 shape: (2000,), batch: 6
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 22300 shape: (2000,), batch: 10
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 22400 shape: (2000,), batch: 4
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.9999997

counter: 24100 shape: (2000,), batch: 7
[1.000000e-05 1.000000e-05 6.856096e-02 ... 1.000000e-05 9.027726e-01
 1.000000e-05]
[9.99999975e-06 9.99999975e-06 6.85609579e-02 ... 9.99999975e-06
 9.02772605e-01 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 24200 shape: (2000,), batch: 12
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 24300 shape: (2000,), batch: 8
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e

counter: 26100 shape: (2000,), batch: 3
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 26200 shape: (2000,), batch: 7
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 26300 shape: (2000,), batch: 7
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975

counter: 27900 shape: (2000,), batch: 12
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 28000 shape: (2000,), batch: 3
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 28100 shape: (2000,), batch: 10
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.999999

counter: 29900 shape: (2000,), batch: 10
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 30000 shape: (2000,), batch: 9
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 30100 shape: (2000,), batch: 10
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.999999

counter: 31800 shape: (2000,), batch: 10
[9.9999997e-06 9.9999997e-06 9.9999997e-06 ... 2.1758769e-02 9.9999997e-06
 9.9999997e-06]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 2.17587687e-02
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 31900 shape: (2000,), batch: 3
[9.9999997e-06 9.9999997e-06 5.5708551e-01 ... 9.9999997e-06 3.1203014e-01
 9.9999997e-06]
[9.99999975e-06 9.99999975e-06 5.57085514e-01 ... 9.99999975e-06
 3.12030137e-01 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 32000 shape: (2000

counter: 33600 shape: (2000,), batch: 18
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 33700 shape: (2000,), batch: 7
[1.000000e-05 1.000000e-05 7.754477e-02 ... 1.000000e-05 1.000000e-05
 1.000000e-05]
[9.99999975e-06 9.99999975e-06 7.75447711e-02 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 33800 shape: (2000,), batch: 18
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.

counter: 35500 shape: (2000,), batch: 2
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 35600 shape: (2000,), batch: 2
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 35700 shape: (2000,), batch: 3
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975

counter: 37500 shape: (2000,), batch: 12
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 37600 shape: (2000,), batch: 2
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 37700 shape: (2000,), batch: 2
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.9999997

counter: 39300 shape: (2000,), batch: 2
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 39400 shape: (2000,), batch: 12
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 39500 shape: (2000,), batch: 8
[9.9999997e-06 9.9999997e-06 9.9999997e-06 ... 9.9999997e-06 9.9999997e-0

counter: 41200 shape: (2000,), batch: 4
[9.9999997e-06 9.9999997e-06 1.9746048e+00 ... 9.9999997e-06 9.9999997e-06
 9.9999997e-06]
[9.99999975e-06 9.99999975e-06 1.97460485e+00 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 41300 shape: (2000,), batch: 6
[1.000000e-05 2.928577e-03 1.000000e-05 ... 1.000000e-05 2.928577e-03
 1.000000e-05]
[9.99999975e-06 2.92857690e-03 9.99999975e-06 ... 9.99999975e-06
 2.92857690e-03 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 41400 shape: (2000,), bat

counter: 43000 shape: (2000,), batch: 6
[9.9999997e-06 9.9999997e-06 9.9999997e-06 ... 1.3772353e+00 9.9999997e-06
 9.9999997e-06]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 1.37723529e+00
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 43100 shape: (2000,), batch: 12
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 43200 shape: (2000,), batch: 7
[1.000000e-05 5.358052e-01 3.4

counter: 44900 shape: (2000,), batch: 2
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 45000 shape: (2000,), batch: 6
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 45100 shape: (2000,), batch: 0
[1.000000e-05 1.000000e-05 1.000000e-05 ... 5.067744e-01 6.503086e-01
 1.0

counter: 46800 shape: (2000,), batch: 4
[9.9999997e-06 9.9999997e-06 1.8471975e+00 ... 9.9999997e-06 9.9999997e-06
 9.9999997e-06]
[9.99999975e-06 9.99999975e-06 1.84719753e+00 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 46900 shape: (2000,), batch: 2
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 47000 shape: (2000,), batch: 6
[1.e-05 1.e-05 1.e-05 ... 1.e-0

counter: 48700 shape: (2000,), batch: 3
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 48800 shape: (2000,), batch: 10
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 48900 shape: (2000,), batch: 3
[9.9999997e-06 9.9999997e-06 9.9999997e-06 ... 1.3460119e-02 9.9999997e-0

counter: 50600 shape: (2000,), batch: 10
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 50700 shape: (2000,), batch: 10
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 50800 shape: (2000,), batch: 12
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999

counter: 52400 shape: (2000,), batch: 10
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 52500 shape: (2000,), batch: 10
[9.9999997e-06 9.9999997e-06 9.9999997e-06 ... 3.0929053e-01 9.9999997e-06
 9.9999997e-06]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 3.09290528e-01
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 52600 shape: (2000,), batch: 10
[1.e-05 1.e-05 1.e-05 ... 1.

counter: 54200 shape: (2000,), batch: 10
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 54300 shape: (2000,), batch: 3
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 54400 shape: (2000,), batch: 3
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.9999997

counter: 56000 shape: (2000,), batch: 10
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 56100 shape: (2000,), batch: 0
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 56200 shape: (2000,), batch: 15
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.999999

counter: 57800 shape: (2000,), batch: 18
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 57900 shape: (2000,), batch: 19
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 58000 shape: (2000,), batch: 6
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.999999

counter: 59800 shape: (2000,), batch: 0
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 59900 shape: (2000,), batch: 6
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 60000 shape: (2000,), batch: 6
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975

counter: 61600 shape: (2000,), batch: 12
[1.000000e-05 1.000000e-05 1.000000e-05 ... 1.000000e-05 1.000000e-05
 3.022684e-01]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 3.02268386e-01]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 61700 shape: (2000,), batch: 8
[9.9999997e-06 9.9999997e-06 9.9999997e-06 ... 9.9999997e-06 1.5061762e+00
 9.9999997e-06]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 1.50617623e+00 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 61800 shape: (2000,), ba

counter: 63400 shape: (2000,), batch: 10
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 63500 shape: (2000,), batch: 11
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 63600 shape: (2000,), batch: 16
[9.9999997e-06 9.9999997e-06 2.0408285e+00 ... 9.9999997e-06 9.9999997e

counter: 65200 shape: (2000,), batch: 3
[9.9999997e-06 9.9999997e-06 9.9999997e-06 ... 2.2962054e-02 9.9999997e-06
 9.9999997e-06]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 2.29620542e-02
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 65300 shape: (2000,), batch: 2
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 65400 shape: (2000,), batch: 2
[1.e-05 1.e-05 1.e-05 ... 1.e-0

counter: 67100 shape: (2000,), batch: 16
[9.9999997e-06 9.9999997e-06 9.9999997e-06 ... 1.7592315e-02 1.4248824e+00
 9.9999997e-06]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 1.75923146e-02
 1.42488241e+00 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 67200 shape: (2000,), batch: 3
[1.000000e-05 1.000000e-05 1.000000e-05 ... 6.714195e-01 1.000000e-05
 1.000000e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 6.71419501e-01
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 67300 shape: (2000,), ba

counter: 69000 shape: (2000,), batch: 0
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 69100 shape: (2000,), batch: 12
[9.9999997e-06 9.9999997e-06 9.9999997e-06 ... 9.9999997e-06 1.4292935e+00
 9.9999997e-06]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 1.42929351e+00 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 69200 shape: (2000,), batch: 1
[1.000000e-05 1.000000e-05 8.5

counter: 70800 shape: (2000,), batch: 0
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 70900 shape: (2000,), batch: 14
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 71000 shape: (2000,), batch: 11
[9.9999997e-06 3.2764297e+00 7.1320655e-03 ... 7.1320655e-03 9.9999997e-

counter: 72600 shape: (2000,), batch: 8
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 72700 shape: (2000,), batch: 12
[1.000000e-05 1.000000e-05 3.900745e-02 ... 1.000000e-05 4.852374e-02
 1.000000e-05]
[9.99999975e-06 9.99999975e-06 3.90074514e-02 ... 9.99999975e-06
 4.85237390e-02 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 72800 shape: (2000,), batch: 17
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.

counter: 74400 shape: (2000,), batch: 10
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 74500 shape: (2000,), batch: 6
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 74600 shape: (2000,), batch: 9
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.9999997

counter: 76200 shape: (2000,), batch: 10
[9.9999997e-06 9.9999997e-06 9.9999997e-06 ... 9.9999997e-06 1.6370721e+00
 9.9999997e-06]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 1.63707209e+00 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 76300 shape: (2000,), batch: 2
[9.9999997e-06 9.9999997e-06 9.9999997e-06 ... 9.9999997e-06 1.5501482e+00
 9.9999997e-06]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 1.55014825e+00 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 76400 shape: (2000

counter: 78100 shape: (2000,), batch: 10
[1.000000e-05 1.000000e-05 1.000000e-05 ... 7.303004e-01 1.000000e-05
 1.000000e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 7.30300426e-01
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 78200 shape: (2000,), batch: 13
[1.8730812e+00 9.9999997e-06 9.9999997e-06 ... 9.9999997e-06 9.9999997e-06
 9.9999997e-06]
[1.87308121e+00 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 78300 shape: (2000,), b

counter: 80000 shape: (2000,), batch: 10
[1.000000e-05 1.000000e-05 1.000000e-05 ... 4.371869e-01 1.000000e-05
 1.000000e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 4.37186897e-01
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 80100 shape: (2000,), batch: 12
[9.9999997e-06 9.9999997e-06 1.2779106e+00 ... 9.9999997e-06 9.9999997e-06
 9.9999997e-06]
[9.99999975e-06 9.99999975e-06 1.27791059e+00 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 80200 shape: (2000,), b

counter: 81800 shape: (2000,), batch: 6
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 81900 shape: (2000,), batch: 1
[9.9999997e-06 9.9999997e-06 1.6386844e+00 ... 9.9999997e-06 9.9999997e-06
 9.9999997e-06]
[9.99999975e-06 9.99999975e-06 1.63868439e+00 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 82000 shape: (2000,), batch: 12
[9.9999997e-06 9.9999997e-06 1

counter: 83600 shape: (2000,), batch: 3
[9.9999997e-06 9.9999997e-06 9.9999997e-06 ... 2.3865683e+00 9.9999997e-06
 9.9999997e-06]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 2.38656831e+00
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 83700 shape: (2000,), batch: 10
[1.00000e-05 1.00000e-05 1.00000e-05 ... 1.00000e-05 5.39506e-01
 1.00000e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 5.39506018e-01 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 83800 shape: (2000,), batch: 3

counter: 85400 shape: (2000,), batch: 17
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 85500 shape: (2000,), batch: 0
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 85600 shape: (2000,), batch: 4
[1.000000e-05 1.000000e-05 1.000000e-05 ... 3.459392e-02 1.000000e-05
 1.

counter: 87300 shape: (2000,), batch: 6
[9.9999997e-06 9.9999997e-06 9.9999997e-06 ... 9.9999997e-06 3.8105437e-01
 9.9999997e-06]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 3.81054372e-01 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 87400 shape: (2000,), batch: 14
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 87500 shape: (2000,), batch: 10
[1.e-05 1.e-05 1.e-05 ... 1.e

counter: 89100 shape: (2000,), batch: 8
[9.9999997e-06 9.9999997e-06 9.9999997e-06 ... 9.9999997e-06 2.1363013e+00
 9.9999997e-06]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 2.13630128e+00 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 89200 shape: (2000,), batch: 0
[9.9999997e-06 9.9999997e-06 1.8156705e+00 ... 9.9999997e-06 9.9999997e-06
 9.9999997e-06]
[9.99999975e-06 9.99999975e-06 1.81567049e+00 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 89300 shape: (2000,

counter: 91000 shape: (2000,), batch: 16
[9.9999997e-06 9.9999997e-06 9.9999997e-06 ... 8.7916565e-01 1.1557724e-01
 9.9999997e-06]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 8.79165649e-01
 1.15577243e-01 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 91100 shape: (2000,), batch: 10
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 91200 shape: (2000,), batch: 17
[1.e-05 1.e-05 1.e-05 ... 1.

counter: 92900 shape: (2000,), batch: 12
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 93000 shape: (2000,), batch: 10
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999975e-06 9.99999975e-06 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']
counter: 93100 shape: (2000,), batch: 14
[1.e-05 1.e-05 1.e-05 ... 1.e-05 1.e-05 1.e-05]
[9.99999975e-06 9.99999

counter: 94700 shape: (2000,), batch: 21
[1.000000e-05 1.000000e-05 9.903972e-01 ... 1.000000e-05 1.000000e-05
 1.000000e-05]
[9.99999975e-06 9.99999975e-06 9.90397215e-01 ... 9.99999975e-06
 9.99999975e-06 9.99999975e-06]
batchs:  ['Skin', 'Pancreas', 'Limb_Muscle', 'Heart', 'Spleen', 'Diaphragm', 'Trachea', 'Tongue', 'Thymus', 'Brain_Non-Myeloid', 'Brain_Myeloid', 'Bladder', 'Large_Intestine', 'BAT', 'GAT', 'MAT', 'SCAT', 'Lung', 'Liver', 'Kidney', 'Aorta', 'Mammary_Gland']


'./tfrecord/tissue_hvg/'

In [6]:
# train (leave spleen out). If you don't want to train the model, you can just load our trained classifier's weight and test it directly.
weight_path = './weight_hvg/'
ref_tf_path = './tfrecord/tissue_hvg/'
tissue_id = 4
concerto_train_inter_supervised_uda(ref_tf_path,weight_path,tissue_id,super_parameters={'batch_size': 128, 'epoch_pretrain': 1,'epoch_classifier': 10, 'lr': 1e-4,'drop_rate': 0.1})

tf_list: ['tf_16.tfrecord', 'tf_20.tfrecord', 'tf_19.tfrecord', 'tf_13.tfrecord', 'tf_6.tfrecord', 'tf_18.tfrecord', 'tf_11.tfrecord', 'tf_2.tfrecord', 'tf_12.tfrecord', 'tf_0.tfrecord', 'tf_21.tfrecord', 'tf_5.tfrecord', 'tf_14.tfrecord', 'tf_7.tfrecord', 'tf_1.tfrecord', 'tf_3.tfrecord', 'tf_15.tfrecord', 'tf_9.tfrecord', 'tf_17.tfrecord', 'tf_10.tfrecord', 'tf_8.tfrecord']
valid_files path: ./tfrecord/tissue_hvg/tf_4.tfrecord
./tfrecord/tissue_hvg/tf_19.tfrecord
Epoch 1, step 5, simclr loss: 9.7194.
Epoch 1, step 10, simclr loss: 9.2289.
./tfrecord/tissue_hvg/tf_13.tfrecord
Epoch 1, step 5, simclr loss: 7.6919.
Epoch 1, step 10, simclr loss: 6.9808.
Epoch 1, step 15, simclr loss: 6.1087.
./tfrecord/tissue_hvg/tf_8.tfrecord
Epoch 1, step 5, simclr loss: 3.9667.
Epoch 1, step 10, simclr loss: 3.4042.
Epoch 1, step 15, simclr loss: 2.7518.
Epoch 1, step 20, simclr loss: 2.1682.
Epoch 1, step 25, simclr loss: 1.6711.
Epoch 1, step 30, simclr loss: 1.1623.
./tfrecord/tissue_hvg/tf_0.tfre

Epoch 0, step 20, train cls loss: 3.7739, train acc: 0.4266
Epoch 0, step 25, train cls loss: 3.3489, train acc: 0.4866
./tfrecord/tissue_hvg/tf_18.tfrecord
Epoch 0, step 5, train cls loss: 6.8115, train acc: 0.0984
Epoch 0, step 10, train cls loss: 5.8682, train acc: 0.0961
Epoch 0, step 15, train cls loss: 5.0214, train acc: 0.1422
Epoch 0, step 20, train cls loss: 4.2450, train acc: 0.2773
./tfrecord/tissue_hvg/tf_17.tfrecord
Epoch 0, step 5, train cls loss: 7.2143, train acc: 0.0703
Epoch 0, step 10, train cls loss: 6.3604, train acc: 0.0859
Epoch 0, step 15, train cls loss: 5.6834, train acc: 0.1224
Epoch 0, step 20, train cls loss: 5.0181, train acc: 0.2043
Epoch 0, step 25, train cls loss: 4.5817, train acc: 0.2628
./tfrecord/tissue_hvg/tf_10.tfrecord
Epoch 0, step 5, train cls loss: 6.2064, train acc: 0.0000
Epoch 0, step 10, train cls loss: 5.5017, train acc: 0.0000
Epoch 0, step 15, train cls loss: 4.8854, train acc: 0.0646
Epoch 0, step 20, train cls loss: 4.2514, train acc:

Epoch 1, step 15, train cls loss: 3.2696, train acc: 0.3526
Epoch 1, step 20, train cls loss: 2.6145, train acc: 0.4879
Epoch 1, step 25, train cls loss: 2.1996, train acc: 0.5719
./tfrecord/tissue_hvg/tf_16.tfrecord
Epoch 1, step 5, train cls loss: 5.2578, train acc: 0.1297
Epoch 1, step 10, train cls loss: 3.9531, train acc: 0.2125
Epoch 1, step 15, train cls loss: 2.9358, train acc: 0.4021
Epoch 1, step 20, train cls loss: 2.3468, train acc: 0.5293
Epoch 1, step 25, train cls loss: 1.9650, train acc: 0.6059
./tfrecord/tissue_hvg/tf_9.tfrecord
Epoch 1, step 5, train cls loss: 3.5136, train acc: 0.4516
Epoch 1, step 10, train cls loss: 2.5712, train acc: 0.5711
Epoch 1, step 15, train cls loss: 2.2260, train acc: 0.6250
Epoch 1, step 20, train cls loss: 1.9961, train acc: 0.6672
Epoch 1, step 25, train cls loss: 1.7712, train acc: 0.7072
./tfrecord/tissue_hvg/tf_19.tfrecord
Epoch 1, step 5, train cls loss: 5.5292, train acc: 0.0422
Epoch 1, step 10, train cls loss: 4.1158, train acc: 

Epoch 3, step 25, train cls loss: 0.8513, train acc: 0.8434
./tfrecord/tissue_hvg/tf_12.tfrecord
Epoch 3, step 5, train cls loss: 0.7771, train acc: 0.8297
Epoch 3, step 10, train cls loss: 0.7888, train acc: 0.8266
Epoch 3, step 15, train cls loss: 0.7143, train acc: 0.8448
Epoch 3, step 20, train cls loss: 0.6853, train acc: 0.8531
Epoch 3, step 25, train cls loss: 0.6707, train acc: 0.8537
./tfrecord/tissue_hvg/tf_21.tfrecord
Epoch 3, step 5, train cls loss: 0.3829, train acc: 0.9531
Epoch 3, step 10, train cls loss: 0.3216, train acc: 0.9664
Epoch 3, step 15, train cls loss: 0.2930, train acc: 0.9729
Epoch 3, step 20, train cls loss: 0.2767, train acc: 0.9754
Epoch 3, step 25, train cls loss: 0.2675, train acc: 0.9778
./tfrecord/tissue_hvg/tf_0.tfrecord
Epoch 3, step 5, train cls loss: 1.2002, train acc: 0.7250
Epoch 3, step 10, train cls loss: 0.9938, train acc: 0.7898
Epoch 3, step 15, train cls loss: 0.8507, train acc: 0.8229
Epoch 3, step 20, train cls loss: 0.7883, train acc: 

Epoch 4, step 20, train cls loss: 0.3976, train acc: 0.9727
Epoch 4, step 25, train cls loss: 0.3739, train acc: 0.9762
./tfrecord/tissue_hvg/tf_8.tfrecord
Epoch 4, step 5, train cls loss: 1.3093, train acc: 0.7281
Epoch 4, step 10, train cls loss: 0.9670, train acc: 0.8195
Epoch 4, step 15, train cls loss: 0.8839, train acc: 0.8391
Epoch 4, step 20, train cls loss: 0.7824, train acc: 0.8594
Epoch 4, step 25, train cls loss: 0.7079, train acc: 0.8766
./tfrecord/tissue_hvg/tf_5.tfrecord
Epoch 4, step 5, train cls loss: 0.9689, train acc: 0.7625
Epoch 4, step 10, train cls loss: 1.1291, train acc: 0.7172
./tfrecord/tissue_hvg/tf_19.tfrecord
Epoch 4, step 5, train cls loss: 0.9796, train acc: 0.7844
Epoch 4, step 10, train cls loss: 1.1834, train acc: 0.7555
./tfrecord/tissue_hvg/tf_0.tfrecord
Epoch 4, step 5, train cls loss: 0.6035, train acc: 0.8875
Epoch 4, step 10, train cls loss: 0.5556, train acc: 0.8969
Epoch 4, step 15, train cls loss: 0.5824, train acc: 0.8870
Epoch 4, step 20, t

./tfrecord/tissue_hvg/tf_17.tfrecord
Epoch 5, step 5, train cls loss: 1.8996, train acc: 0.4531
Epoch 5, step 10, train cls loss: 1.3782, train acc: 0.6375
Epoch 5, step 15, train cls loss: 1.1654, train acc: 0.7240
Epoch 5, step 20, train cls loss: 1.0057, train acc: 0.7742
Epoch 5, step 25, train cls loss: 0.9631, train acc: 0.7956
./tfrecord/tissue_hvg/tf_5.tfrecord
Epoch 5, step 5, train cls loss: 1.1629, train acc: 0.7781
Epoch 5, step 10, train cls loss: 1.1024, train acc: 0.7680
./tfrecord/tissue_hvg/tf_11.tfrecord
Epoch 5, step 5, train cls loss: 0.3104, train acc: 0.9937
Epoch 5, step 10, train cls loss: 0.4138, train acc: 0.9828
Epoch 5, step 15, train cls loss: 0.3768, train acc: 0.9854
./tfrecord/tissue_hvg/tf_0.tfrecord
Epoch 5, step 5, train cls loss: 0.7683, train acc: 0.8328
Epoch 5, step 10, train cls loss: 0.6546, train acc: 0.8656
Epoch 5, step 15, train cls loss: 0.5578, train acc: 0.8906
Epoch 5, step 20, train cls loss: 0.5481, train acc: 0.8949
Epoch 5, step 25, 

Epoch 7, step 20, train cls loss: 0.4534, train acc: 0.9090
Epoch 7, step 25, train cls loss: 0.4377, train acc: 0.9137
./tfrecord/tissue_hvg/tf_2.tfrecord
Epoch 7, step 5, train cls loss: 0.7039, train acc: 0.8125
Epoch 7, step 10, train cls loss: 0.7768, train acc: 0.8125
Epoch 7, step 15, train cls loss: 0.6413, train acc: 0.8641
Epoch 7, step 20, train cls loss: 0.5706, train acc: 0.8902
Epoch 7, step 25, train cls loss: 0.6068, train acc: 0.8838
./tfrecord/tissue_hvg/tf_17.tfrecord
Epoch 7, step 5, train cls loss: 1.1136, train acc: 0.7406
Epoch 7, step 10, train cls loss: 0.9695, train acc: 0.7844
Epoch 7, step 15, train cls loss: 0.8011, train acc: 0.8354
Epoch 7, step 20, train cls loss: 0.6991, train acc: 0.8648
Epoch 7, step 25, train cls loss: 0.7212, train acc: 0.8672
./tfrecord/tissue_hvg/tf_19.tfrecord
Epoch 7, step 5, train cls loss: 1.0483, train acc: 0.8000
Epoch 7, step 10, train cls loss: 0.7923, train acc: 0.8477
./tfrecord/tissue_hvg/tf_10.tfrecord
Epoch 7, step 5,

Epoch 8, step 20, train cls loss: 0.6508, train acc: 0.8531
Epoch 8, step 25, train cls loss: 0.5853, train acc: 0.8747
./tfrecord/tissue_hvg/tf_17.tfrecord
Epoch 8, step 5, train cls loss: 1.6338, train acc: 0.6656
Epoch 8, step 10, train cls loss: 1.2505, train acc: 0.7570
Epoch 8, step 15, train cls loss: 1.0000, train acc: 0.8125
Epoch 8, step 20, train cls loss: 0.8581, train acc: 0.8426
Epoch 8, step 25, train cls loss: 0.8885, train acc: 0.8444
./tfrecord/tissue_hvg/tf_9.tfrecord
Epoch 8, step 5, train cls loss: 0.6953, train acc: 0.8578
Epoch 8, step 10, train cls loss: 0.5170, train acc: 0.9172
Epoch 8, step 15, train cls loss: 0.4451, train acc: 0.9375
Epoch 8, step 20, train cls loss: 0.4403, train acc: 0.9402
Epoch 8, step 25, train cls loss: 0.4101, train acc: 0.9475
./tfrecord/tissue_hvg/tf_19.tfrecord
Epoch 8, step 5, train cls loss: 1.0941, train acc: 0.7500
Epoch 8, step 10, train cls loss: 0.8368, train acc: 0.8195
./tfrecord/tissue_hvg/tf_7.tfrecord
Epoch 8, step 5, 

Epoch 9, step 20, train cls loss: 0.5733, train acc: 0.9152
Epoch 9, step 25, train cls loss: 0.5265, train acc: 0.9278
./tfrecord/tissue_hvg/tf_3.tfrecord
Epoch 9, step 5, train cls loss: 1.5015, train acc: 0.6734
Epoch 9, step 10, train cls loss: 1.0759, train acc: 0.7812
Epoch 9, step 15, train cls loss: 0.8569, train acc: 0.8354
Epoch 9, step 20, train cls loss: 0.7579, train acc: 0.8625
Epoch 9, step 25, train cls loss: 0.7224, train acc: 0.8731
./tfrecord/tissue_hvg/tf_11.tfrecord
Epoch 9, step 5, train cls loss: 0.2287, train acc: 0.9984
Epoch 9, step 10, train cls loss: 0.3047, train acc: 0.9922
Epoch 9, step 15, train cls loss: 0.2878, train acc: 0.9937
./tfrecord/tissue_hvg/tf_5.tfrecord
Epoch 9, step 5, train cls loss: 0.8153, train acc: 0.8234
Epoch 9, step 10, train cls loss: 0.8511, train acc: 0.8102


'./weight_hvg/'

In [17]:
# test (only spleen)
model_path = './weight_hvg/'
ref_tf_path = './tfrecord/tissue_hvg/'
tissue_id = 4
ari = concerto_test_inter_supervised(model_path,ref_tf_path,tissue_id,super_parameters = {'batch_size': 64, 'epoch': 4, 'lr': 1e-5,'drop_rate': 0.1})
print('ari:{}'.format(ari))

load all tf in memory time(s) 0.016609668731689453
test time 2.7924892902374268
source_id len 3776
ari:0.9430769278529922
